# Generated by Django 6.0.1 on 2026-01-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThreatWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("device_id", models.CharField(max_length=64)),
                ("sos_id", models.CharField(blank=True, max_length=128, null=True)),
                ("window_sec", models.PositiveSmallIntegerField()),
                ("hz", models.PositiveSmallIntegerField()),
                ("t_start", models.CharField(max_length=32)),
                ("t_end", models.CharField(max_length=32)),
                ("sample_count", models.PositiveSmallIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device_id", "created_at"],
                        name="ingest_thre_device__56276a_idx",
                    ),
                    models.Index(
                        fields=["sos_id"], name="ingest_thre_sos_id_58cfe8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ThreatSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveSmallIntegerField()),
                ("time", models.CharField(max_length=32)),
                ("ax", models.FloatField()),
                ("ay", models.FloatField()),
                ("az", models.FloatField()),
                ("ppg1", models.IntegerField()),
                ("ppg2", models.IntegerField(blank=True, null=True)),
                ("ppg3", models.IntegerField(blank=True, null=True)),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="ingest.threatwindow",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["window", "seq"], name="ingest_thre_window__71aa59_idx"
                    )
                ],
                "unique_together": {("window", "seq")},
            },
        ),
    ]
