# Generated by Django 6.0.1 on 2026-01-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatsample',
            old_name='ppg1',
            new_name='ppg_green',
        ),
        migrations.RenameField(
            model_name='threatsample',
            old_name='ppg2',
            new_name='ppg_ir',
        ),
        migrations.RenameField(
            model_name='threatsample',
            old_name='ppg3',
            new_name='ppg_red',
        ),
    ]
