# Generated by Django 6.0.1 on 2026-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True, help_text="전용 워치 device_id", max_length=100
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("THREAT", "상시보고"), ("PERIODIC", "주기보고")],
                        help_text="THREAT=상시보고, PERIODIC=주기보고",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("PPG", "PPG"), ("IMU", "IMU")],
                        help_text="PPG 또는 IMU",
                        max_length=10,
                    ),
                ),
                (
                    "timestamp",
                    models.BigIntegerField(
                        help_text="UNIX timestamp milliseconds. 분석 결과가 대표하는 기준 시각"
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        blank=True,
                        help_text="위험 확률값. 결과가 없으면 null",
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[("LOW", "하"), ("MIDDLE", "중"), ("HIGH", "상")],
                        help_text="LOW/MIDDLE/HIGH. 결과가 없으면 null",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "risk_detected",
                    models.BooleanField(
                        blank=True,
                        help_text="위험 감지 여부. 결과가 없으면 null",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analysis_result",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "timestamp"],
                        name="analysis_re_device__02e38b_idx",
                    ),
                    models.Index(fields=["mode"], name="analysis_re_mode_5a3001_idx"),
                    models.Index(
                        fields=["event_type"], name="analysis_re_event_t_7d3e32_idx"
                    ),
                    models.Index(
                        fields=["risk_detected"], name="analysis_re_risk_de_df6f5e_idx"
                    ),
                ],
            },
        ),
    ]
