# Generated by Django 6.0.1 on 2026-05-04 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Protectee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="전용 워치 device_id",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="보호 대상자 이름",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "남성"),
                            ("FEMALE", "여성"),
                            ("UNKNOWN", "미상"),
                        ],
                        default="UNKNOWN",
                        help_text="보호 대상자 성별",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "protectee",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("THREAT", "상시보고"),
                            ("PERIODIC", "주기보고"),
                            ("CALIBRATION", "캘리브레이션"),
                        ],
                        help_text="THREAT=상시보고, PERIODIC=주기보고, CALIBRATION=캘리브레이션",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="세션 종료 시각. null이면 진행 중",
                        null=True,
                    ),
                ),
                (
                    "protectee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_sessions",
                        to="monitoring.protectee",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SensorWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_rate_hz", models.PositiveIntegerField(default=25)),
                ("duration_sec", models.PositiveIntegerField(default=12)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("ppg_green", models.JSONField(help_text="PPG green 배열")),
                (
                    "x",
                    models.JSONField(
                        blank=True,
                        help_text="IMU x 배열. 캘리브레이션 모드에서는 null",
                        null=True,
                    ),
                ),
                (
                    "y",
                    models.JSONField(
                        blank=True,
                        help_text="IMU y 배열. 캘리브레이션 모드에서는 null",
                        null=True,
                    ),
                ),
                (
                    "z",
                    models.JSONField(
                        blank=True,
                        help_text="IMU z 배열. 캘리브레이션 모드에서는 null",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_windows",
                        to="monitoring.monitoringsession",
                    ),
                ),
            ],
            options={
                "db_table": "sensor_window",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="monitoringsession",
            index=models.Index(
                fields=["mode", "ended_at"], name="monitoring__mode_00176f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringsession",
            index=models.Index(
                fields=["protectee", "started_at"],
                name="monitoring__protect_498352_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensorwindow",
            index=models.Index(
                fields=["session"], name="sensor_wind_session_5c4452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensorwindow",
            index=models.Index(
                fields=["started_at"], name="sensor_wind_started_62388b_idx"
            ),
        ),
    ]
