# Generated by Django 6.0.1 on 2026-06-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringsession",
            name="mode",
            field=models.CharField(
                choices=[
                    ("THREAT", "이벤트보고"),
                    ("PERIODIC", "주기보고"),
                    ("CALIBRATION", "캘리브레이션"),
                ],
                help_text="THREAT=상시보고, PERIODIC=주기보고, CALIBRATION=캘리브레이션",
                max_length=20,
            ),
        ),
    ]
