# Generated by Django 5.2.7 on 2026-06-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_alter_monitoringsession_mode"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sensorwindow",
            new_name="monitoring__session_c09bc6_idx",
            old_name="sensor_wind_session_5c4452_idx",
        ),
        migrations.RenameIndex(
            model_name="sensorwindow",
            new_name="monitoring__started_037ede_idx",
            old_name="sensor_wind_started_62388b_idx",
        ),
        migrations.AlterModelTable(
            name="sensorwindow",
            table="monitoring_window",
        ),
    ]
