# Generated by Django 5.2.6 on 2026-07-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "monitoring",
            "0003_rename_sensor_wind_session_5c4452_idx_monitoring__session_c09bc6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringsession",
            name="last_received_at",
            field=models.DateTimeField(
                blank=True, help_text="가장 최근 윈도우가 서버에 수신된 시각", null=True
            ),
        ),
        migrations.AddField(
            model_name="monitoringsession",
            name="window_count",
            field=models.PositiveIntegerField(default=0, help_text="현재 세션에 수신된 윈도우 개수"),
        ),
        migrations.AlterField(
            model_name="monitoringsession",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="protectee",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sensorwindow",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
