# Generated by Django 5.2.6 on 2026-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_sensorwindow_protectee'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringsession',
            name='sos_detected_at',
            field=models.DateTimeField(blank=True, help_text='이 세션에서 SOS를 플랫폼으로 전송한 시각. null이면 아직 전송하지 않음', null=True),
        ),
    ]
