# Generated by Django 6.0.1 on 2026-06-11 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitoring", "0002_alter_monitoringsession_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("pos_success", models.BooleanField()),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("accuracy_h", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "protectee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_data",
                        to="monitoring.protectee",
                    ),
                ),
            ],
            options={
                "db_table": "geo_data",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "timestamp"],
                        name="geo_data_device__7867d7_idx",
                    ),
                    models.Index(
                        fields=["protectee", "timestamp"],
                        name="geo_data_protect_883844_idx",
                    ),
                    models.Index(
                        fields=["pos_success"], name="geo_data_pos_suc_5740fc_idx"
                    ),
                ],
            },
        ),
    ]
