# Generated by Django 6.0.1 on 2026-05-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="중앙서버에서 전달받은 전용 워치 device_id",
                        max_length=100,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="GPS 측정 시간. API에서는 UNIX ms로 받고, DB에는 UTC DateTime으로 저장",
                    ),
                ),
                ("latitude", models.FloatField(help_text="위도")),
                ("longitude", models.FloatField(help_text="경도")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="성신서버 DB 저장 시간"
                    ),
                ),
                (
                    "protectee",
                    models.ForeignKey(
                        help_text="device_id로 매핑된 보호 대상자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_data",
                        to="monitoring.protectee",
                    ),
                ),
            ],
            options={
                "db_table": "geo_data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device_id", "timestamp"],
                        name="geo_data_device__7867d7_idx",
                    ),
                    models.Index(
                        fields=["protectee", "timestamp"],
                        name="geo_data_protect_883844_idx",
                    ),
                ],
            },
        ),
    ]
