# Generated by Django 5.2.6 on 2026-07-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_geoprocesseddata_geotripanomalyresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geodata",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="geoprocesseddata",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="geotripanomalyresult",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
