# Generated by Django 5.2.6 on 2026-07-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0003_alter_geodata_id_alter_geoprocesseddata_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoprocesseddata",
            name="latitude",
            field=models.FloatField(blank=True, db_column="Latitude", null=True),
        ),
        migrations.AlterField(
            model_name="geoprocesseddata",
            name="longitude",
            field=models.FloatField(blank=True, db_column="Longitude", null=True),
        ),
    ]
