# Generated by Django 6.0.1 on 2026-06-16 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "monitoring",
            "0003_rename_sensor_wind_session_5c4452_idx_monitoring__session_c09bc6_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApneaSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=100)),
                ("started_at", models.DateTimeField()),
                ("baseline_ready", models.BooleanField(default=False)),
                ("baseline_stats", models.JSONField(blank=True, null=True)),
                ("model_config", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ApneaResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("wear_valid", models.BooleanField(null=True)),
                ("wear_label", models.IntegerField(null=True)),
                ("is_baseline", models.BooleanField(default=False)),
                ("beat_results", models.JSONField(blank=True, null=True)),
                ("p_apnea", models.FloatField(null=True)),
                ("p_apnea_smooth", models.FloatField(null=True)),
                ("pred_label", models.IntegerField(null=True)),
                ("pred_status", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "sensor_window",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apnea_result",
                        to="monitoring.sensorwindow",
                    ),
                ),
            ],
            options={
                "db_table": "apnea_result",
                "ordering": ["-processed_at"],
            },
        ),
    ]
