# Generated by Django 5.2.6 on 2026-07-06 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppg", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apneasession",
            name="model_config",
        ),
    ]
